export const moduelA={
    state:{
        list:[
            {
                name:'vivo-X20Plus屏幕指纹版',
                info:'逆光也清晰，照亮你的美',
                price:3596,
                img:'../img/h.a8add7c.jpg',
                n:0,
                id:1001,
            },
            {
                name:'华为mate10Plus',
                info:'真正的人工智能芯片',
                price:4999,
                img:'../img/v.6138fcf.jpg',
                n:0,
                id:1002,
            },
            {
                name:'vivo-X20Plus屏幕指纹版',
                info:'逆光也清晰，照亮你的美',
                price:3596,
                img:'../img/h.a8add7c.jpg',
                n:0,
                id:1003,
            },
            {
                name:'vivo-X20Plus屏幕指纹版',
                info:'逆光也清晰，照亮你的美',
                price:3596,
                img:'../img/h.a8add7c.jpg',
                n:0,
                id:1001,
            },
            {
                name:'华为mate10Plus',
                info:'真正的人工智能芯片',
                price:4999,
                img:'../img/v.6138fcf.jpg',
                n:0,
                id:1002,
            },
            {
                name:'vivo-X20Plus屏幕指纹版',
                info:'逆光也清晰，照亮你的美',
                price:3596,
                img:'../img/h.a8add7c.jpg',
                n:0,
                id:1003,
            },
            {
                name:'vivo-X20Plus屏幕指纹版',
                info:'逆光也清晰，照亮你的美',
                price:3596,
                img:'../img/h.a8add7c.jpg',
                n:0,
                id:1001,
            },
            {
                name:'华为mate10Plus',
                info:'真正的人工智能芯片',
                price:4999,
                img:'../img/v.6138fcf.jpg',
                n:0,
                id:1002,
            },
            {
                name:'vivo-X20Plus屏幕指纹版',
                info:'逆光也清晰，照亮你的美',
                price:3596,
                img:'../img/h.a8add7c.jpg',
                n:0,
                id:1003,
            },
        ],
    },
    mutations:{

    }
}